### ISSUE TITLE
Where is FromEnv defined?

### ISSUE THREAD

**Issue by wpoosanguansit** [rcook/aws-easy#2]
Hi,

I am trying to find where
```
                                FromEnv
                                        "AWS_ACCESS_KEY_ID"
                                        "AWS_SECRET_ACCESS_KEY"
                                        (Just "AWS_SESSION_TOKEN")
                                        (Just "AWS_REGION")
```
is defined but I could not see where it is imported from.  Could you point me to that?  Thanks for your help.

**Comment by rcook** [comment]
Sure: https://github.com/rcook/aws-easy/blob/master/app/Main.hs#L27

`FromEnv` is one of the constructors of `Credentials` (https://www.stackage.org/haddock/lts-13.10/amazonka-1.6.1/Network-AWS.html#v:FromEnv).
